#!/bin/zsh
# init-claude-setup.sh
# One-time initialization: copies existing Claude config files into
# llm-wiki/claude-setup/ so it becomes the source of truth.
#
# Safe to re-run — skips files that already exist in claude-setup/.
# After this: run link-claude-to-dotfiles.sh to wire up the symlinks.
#
# Usage: ./scripts/init-claude-setup.sh

set -euo pipefail

WIKI="$HOME/repos/llm-wiki"
SETUP="$WIKI/claude-setup"
DOTFILES_CLAUDE="$HOME/dotfiles/claude/.claude"
CLAUDE_DIR="$HOME/.claude"

copy_if_missing() {
  local src="$1"
  local dst="$2"
  if [[ -e "$dst" ]]; then
    echo "  skip (exists): $dst"
    return
  fi
  if [[ ! -e "$src" ]]; then
    echo "  warn (missing source): $src"
    return
  fi
  cp "$src" "$dst"
  echo "  copied: $(basename "$src")"
}

echo "=== Initializing llm-wiki/claude-setup/ from existing sources ==="
echo ""

# ── Top-level config files ──────────────────────────────────────────────────
echo "Top-level config:"
mkdir -p "$SETUP"
copy_if_missing "$DOTFILES_CLAUDE/CLAUDE.md"      "$SETUP/CLAUDE.md"
copy_if_missing "$DOTFILES_CLAUDE/settings.json"  "$SETUP/settings.json"
copy_if_missing "$DOTFILES_CLAUDE/keybindings.json" "$SETUP/keybindings.json"

# ── Rules ───────────────────────────────────────────────────────────────────
# Rules live in ~/.claude/rules/ as plain files (not in dotfiles yet).
echo ""
echo "Rules (from ~/.claude/rules/):"
mkdir -p "$SETUP/rules"
for f in "$CLAUDE_DIR/rules/"*.md; do
  [[ -f "$f" ]] || continue
  copy_if_missing "$f" "$SETUP/rules/$(basename "$f")"
done

# ── Agents ──────────────────────────────────────────────────────────────────
echo ""
echo "Agents (from ~/dotfiles/claude/.claude/agents/):"
mkdir -p "$SETUP/agents"
for f in "$DOTFILES_CLAUDE/agents/"*.md; do
  [[ -f "$f" ]] || continue
  copy_if_missing "$f" "$SETUP/agents/$(basename "$f")"
done

# ── Plugin config ────────────────────────────────────────────────────────────
echo ""
echo "Plugin config:"
mkdir -p "$SETUP/plugins"
copy_if_missing "$DOTFILES_CLAUDE/plugins/config.json"             "$SETUP/plugins/config.json"
copy_if_missing "$DOTFILES_CLAUDE/plugins/known_marketplaces.json" "$SETUP/plugins/known_marketplaces.json"

# ── Templates ────────────────────────────────────────────────────────────────
echo ""
echo "Templates:"
mkdir -p "$SETUP/templates/project-template/docs"
mkdir -p "$SETUP/templates/hooks"
copy_if_missing "$DOTFILES_CLAUDE/templates/plan.md"                          "$SETUP/templates/plan.md"
copy_if_missing "$DOTFILES_CLAUDE/templates/hooks/settings.json"              "$SETUP/templates/hooks/settings.json"
copy_if_missing "$DOTFILES_CLAUDE/templates/hooks/README.md"                  "$SETUP/templates/hooks/README.md"
copy_if_missing "$DOTFILES_CLAUDE/templates/project-template/CLAUDE.md"       "$SETUP/templates/project-template/CLAUDE.md"
copy_if_missing "$DOTFILES_CLAUDE/templates/project-template/docs/architecture.md" "$SETUP/templates/project-template/docs/architecture.md"
copy_if_missing "$DOTFILES_CLAUDE/templates/project-template/docs/decisions.md"    "$SETUP/templates/project-template/docs/decisions.md"
copy_if_missing "$DOTFILES_CLAUDE/templates/project-template/docs/todo.md"         "$SETUP/templates/project-template/docs/todo.md"

# ── Skills ───────────────────────────────────────────────────────────────────
echo ""
echo "Skills (from ~/dotfiles/claude/.claude/skills/):"
for skill_dir in "$DOTFILES_CLAUDE/skills/"/*/; do
  [[ -d "$skill_dir" ]] || continue
  skill_name="$(basename "$skill_dir")"
  mkdir -p "$SETUP/skills/$skill_name"
  copy_if_missing "$skill_dir/SKILL.md" "$SETUP/skills/$skill_name/SKILL.md"
done

# ── Shared (generated — track source, not output) ───────────────────────────
# shared/AGENTS.md is auto-generated by sync-agent-rules.sh from the rules files.
# We DO NOT copy it here — it stays in ~/dotfiles/shared/ as a generated artifact.
# Edit rules in claude-setup/rules/, then run sync-agent-rules.sh to regenerate.
mkdir -p "$SETUP/shared"
echo ""
echo "Shared: (shared/AGENTS.md is generated — regenerate with sync-agent-rules.sh)"

echo ""
echo "=== Done ==="
echo ""
echo "Next step: wire up symlinks with:"
echo "  ./scripts/link-claude-to-dotfiles.sh"
